// apps/provider/src/lib/components/schedule/AppointmentSeriesForm.svelte
<script lang="ts">
  import { createAppointmentSeries } from "$lib/api";
  import { Field, vaccines, type Vaccine } from "@impfen/common";
  import dayjs from "dayjs";
  import { locale, t } from "svelte-intl-precompile";

  export let onSuccess: () => void | undefined = undefined;

  let startDate = dayjs()
    .utc()
    .add(1, "day")
    .set("hour", 8)
    .set("minute", 0)
    .format("YYYY-MM-DD");
  let hourFrom = "08:00";
  let hourTo = "18:00";
  let slotCount = 5;
  let interval = 15;
  let vaccine: Vaccine;
  let isSubmitting = false;

  const handleSubmit = async () => {
    isSubmitting = true;
    const startAt = dayjs(startDate)
      .set("hour", Number(hourFrom.split(":")[0]))
      .set("minute", Number(hourFrom.split(":")[1]));

    const endAt = dayjs(startDate)
      .set("hour", Number(hourTo.split(":")[0]))
      .set("minute", Number(hourTo.split(":")[1]));

    await createAppointmentSeries(
      startAt,
      endAt,
      Number(interval),
      vaccine,
      slotCount
    ).then((result) => {
      if (onSuccess) {
        onSuccess();
      }

      isSubmitting = false;

      return result;
    });
  };
</script>

<form
  name="appointment-series-form"
  class="stack-v gap-m"
  on:submit|preventDefault={handleSubmit}
>
  <Field
    name="startDate"
    label={$t("provider.schedule.appointment-series-form.start-at.label")}
    required
    ><input
      type="date"
      name="startDate"
      required
      min={dayjs().format("YYYY-MM-DD")}
      max={dayjs().add(30, "days").format("YYYY-MM-DD")}
      bind:value={startDate}
    /></Field
  >

  <Field
    name="vaccine"
    label={$t("provider.schedule.appointment-series-form.vaccine-label")}
    description={$t(
      "provider.schedule.appointment-series-form.vaccine.description"
    )}
    required
  >
    <select name="vaccine" required bind:value={vaccine}>
      {#each Object.keys(vaccines["de"]) as vaccineKey}
        <option value={vaccineKey}>{vaccines[$locale][vaccineKey].name}</option>
      {/each}
    </select>
  </Field>

  <div class="flex flex-row gap-m">
    <Field
      name="hourFrom"
      label={$t("provider.schedule.appointment-series-form.hour-from.label")}
      required
      ><input
        type="time"
        name="hourFrom"
        required
        bind:value={hourFrom}
      /></Field
    >

    <Field
      name="hourTo"
      label={$t("provider.schedule.appointment-series-form.hour-end.label")}
      required
      ><input type="time" name="hourTo" required bind:value={hourTo} /></Field
    >
  </div>

  <div class="flex flex-row gap-m">
    <!-- {...register("slotCount", {
        valueAsNumber: true,
        required: t({
          id: "provider.schedule.appointment-series-form.slots.error.required",
          message: "Bitte gegen Sie die Anzahl der Impfdosen ein",
        }),
        min: {
          value: 1,
          message: t({
            id: "provider.schedule.appointment-series-form.slots.error.min",
            message:
              "Die minimale Anzahl der Impfdosen pro Termin beträgt 1",
          }),
        },
        max: {
          value: 50,
          message: t({
            id: "provider.schedule.appointment-series-form.slots.error.max",
            message:
              "Die maximale Anzahl der Impfdosen pro Termin beträgt 50",
          }),
        },
      })} -->
    <Field
      name="slotCount"
      label={$t("provider.schedule.appointment-series-form.slots.label")}
      required
      description={$t(
        "provider.schedule.appointment-series-form.slots.description"
      )}
      ><input
        type="number"
        name="slotCount"
        bind:value={slotCount}
        required
        min={1}
        max={50}
      /></Field
    >

    <!-- {...register("interval", {
        valueAsNumber: true,
        required: t({
          id: "provider.schedule.appointment-series-form.duration.error-required",
          message: "Bitte gegen Sie die Anzahl der Impfdosen ein",
        }),
        min: {
          value: 5,
          message: t({
            id: "provider.schedule.appointment-series-form.duration.error.min",
            message:
              "Die minimale Dauer eines Impftermins beträgt 5 Minuten",
          }),
        },
        max: {
          value: 240,
          message: t({
            id: "provider.schedule.appointment-series-form.duration.error.max",
            message:
              "Die maximale Dauer eines Impftermins beträgt 240 Minuten",
          }),
        },
      })} -->

    <Field
      name="interval"
      label={$t("provider.schedule.appointment-series-form.duration.label")}
      required
      description={$t(
        "provider.schedule.appointment-series-form.duration.description"
      )}
    >
      <input type="number" name="interval" required bind:value={interval} />
    </Field>
  </div>

  <!-- <Field
        label={$t("provider.schedule.appointment-series-form.vaccine-label")}
        description={$t("provider.schedule.appointment-series-form.vaccine.description",
          message: "Der verimpfte Impfstoff",
        })}
        required
        {...register("vaccine", {
          required: t({
            id: "provider.schedule.appointment-series-form.vaccine.error-required",
            message: "Bitte gegen Sie den Impfstoff an",
          }),
        })} -->

  <button type="submit" class="button primary m" disabled={isSubmitting}>
    {$t("provider.schedule.appointment-series-form.button")}
  </button>
</form>

// apps/provider/src/components/schedule/AppointmentSeriesForm.tsx
import {
  Button,
  Form,
  InputField,
  SelectField,
  Vaccine,
  vaccines,
} from "@impfen/common";
import { t, Trans } from "@lingui/macro";
import dayjs from "dayjs";
import {
  FormProvider,
  Resolver,
  SubmitHandler,
  useForm,
} from "react-hook-form";
import { createAppointmentSeries } from "stores/app";

interface FormData {
  startDate: string;
  hourFrom: string;
  hourTo: string;
  interval: number;
  slotCount: number;
  vaccine: Vaccine;
}

const resolver: Resolver<FormData> = async (values) => {
  const errors: any = {};

  if (values.slotCount > 50) {
    errors.slots = t({
      id: "provider.schedule.create-appointment-series-modal.too-many-slots",
    });
  }

  if (values.slotCount < 1) {
    errors.slots = t({
      id: "provider.schedule.create-appointment-series-modal.too-few-slots",
    });
  }

  return {
    values,
    errors,
  };
};

interface AppointmentSeriesFormProps {
  onSuccess?: () => void;
}

export const AppointmentSeriesForm: React.FC<AppointmentSeriesFormProps> = ({
  onSuccess,
}) => {
  const methods = useForm<FormData>({
    mode: "onBlur",
    defaultValues: {
      startDate: dayjs()
        .utc()
        .add(1, "day")
        .set("hour", 8)
        .set("minute", 0)
        .format("YYYY-MM-DD"),
      hourFrom: "08:00",
      hourTo: "18:00",
      slotCount: 5,
      interval: 15,
    },
    resolver,
  });

  const { register, handleSubmit, formState } = methods;

  const onSubmit: SubmitHandler<FormData> = async (data) => {
    const startAt = dayjs(data.startDate)
      .set("hour", Number(data.hourFrom.split(":")[0]))
      .set("minute", Number(data.hourFrom.split(":")[1]));
    const endAt = dayjs(data.startDate)
      .set("hour", Number(data.hourTo.split(":")[0]))
      .set("minute", Number(data.hourTo.split(":")[1]));
    await createAppointmentSeries(
      startAt,
      endAt,
      Number(data.interval),
      data.vaccine,
      data.slotCount
    ).then((result) => {
      if (onSuccess) {
        onSuccess();
      }

      return result;
    });
  };

  return (
    <FormProvider {...methods}>
      <Form name="appointment-series-modal" onSubmit={handleSubmit(onSubmit)}>
        <div className="flex flex-col gap-6">
          <div className="flex flex-row gap-6">
            <InputField
              label={t({
                id: "provider.schedule.create.appointment-series-modal.start-at.label",
                message: "Datum",
              })}
              required
              type="date"
              {...register("startDate", {
                required: true,
                valueAsDate: true,
              })}
            />

            <InputField
              label={t({
                id: "provider.schedule.create.appointment-series-modal.hour-from.label",
                message: "Von",
              })}
              required
              type="time"
              {...register("hourFrom", {
                required: true,
              })}
            />

            <InputField
              label={t({
                id: "provider.schedule.create.appointment-series-modal.hour-end.label",
                message: "Bis",
              })}
              required
              type="time"
              {...register("hourTo", {
                required: true,
              })}
            />
          </div>

          <div className="flex flex-row gap-6">
            <InputField
              label={t({
                id: "provider.schedule.appointment-series-modal.slots.label",
                message: "Anzahl Impfdosen",
              })}
              type="number"
              required
              description={t({
                id: "provider.schedule.appointment-series-modal.slots.description",
                message: "Die verfügbaren Impfdosen pro Zeiteinheit.",
              })}
              {...register("slotCount", {
                valueAsNumber: true,
                required: t({
                  id: "provider.schedule.appointment-series-modal.slots.error.required",
                  message: "Bitte gegen Sie die Anzahl der Impfdosen ein",
                }),
                min: {
                  value: 1,
                  message: t({
                    id: "provider.schedule.appointment-series-modal.slots.error.min",
                    message:
                      "Die minimale Anzahl der Impfdosen pro Termin beträgt 1",
                  }),
                },
                max: {
                  value: 50,
                  message: t({
                    id: "provider.schedule.appointment-series-modal.slots.error.max",
                    message:
                      "Die maximale Anzahl der Impfdosen pro Termin beträgt 50",
                  }),
                },
              })}
            />

            <InputField
              label={t({
                id: "provider.schedule.appointment-series-modal.duration.label",
                message: "Vstl. Dauer",
              })}
              type="number"
              required
              description={t({
                id: "provider.schedule.appointment-series-modal.duration.description",
                message: "Vstl. Dauer pro Impftermin in Minuten",
              })}
              {...register("interval", {
                valueAsNumber: true,
                required: t({
                  id: "provider.schedule.appointment-series-modal.duration.error-required",
                  message: "Bitte gegen Sie die Anzahl der Impfdosen ein",
                }),
                min: {
                  value: 5,
                  message: t({
                    id: "provider.schedule.appointment-series-modal.duration.error.min",
                    message:
                      "Die minimale Dauer eines Impftermins beträgt 5 Minuten",
                  }),
                },
                max: {
                  value: 240,
                  message: t({
                    id: "provider.schedule.appointment-series-modal.duration.error.max",
                    message:
                      "Die maximale Dauer eines Impftermins beträgt 240 Minuten",
                  }),
                },
              })}
            />
          </div>

          <div className="flex flex-row gap-6">
            <SelectField
              label={t({
                id: "provider.schedule.appointment-series-modal.vaccine-label",
                message: "Impfstoff",
              })}
              options={Object.keys(vaccines.de).map((vaccineKey) => {
                return {
                  label: vaccines.de[vaccineKey as Vaccine].name,
                  value: vaccineKey,
                };
              })}
              description={t({
                id: "provider.schedule.appointment-series-modal.vaccine.description",
                message: "Der verimpfte Impfstoff",
              })}
              required
              {...register("vaccine", {
                required: t({
                  id: "provider.schedule.appointment-series-modal.vaccine.error-required",
                  message: "Bitte gegen Sie den Impfstoff an",
                }),
              })}
            />
          </div>

          <Button disabled={!formState.isValid || formState.isSubmitting}>
            <Trans id="provider.schedule.create.appointment-series-modal.button">
              Speichern
            </Trans>
          </Button>
        </div>
      </Form>
    </FormProvider>
  );
};
