// apps/provider/src/components/schedule/AppointmentCard.tsx
import { Button, Vaccine, vaccines } from "@impfen/common";
import { Trans } from "@lingui/macro";
import { useLingui } from "@lingui/react";
import clsx from "clsx";
import { useCallback, useState } from "react";
import { cancelAppointment } from "stores/app";
import type { Appointment } from "vanellus";
import { AppointmentStatus } from "vanellus";

export interface AppointmentCardProps {
  appointment: Appointment;
  className?: string;
  border?: true | undefined;
}

export const AppointmentCard: React.FC<AppointmentCardProps> = ({
  children,
  appointment,
  className,
  border = false,
  ...props
}) => {
  const { i18n } = useLingui();
  let [actualAppointment, setActualAppointment] =
    useState<Appointment>(appointment);

  const handleCancelAppointment = useCallback(async () => {
    cancelAppointment(appointment).then(setActualAppointment);
  }, [appointment]);

  return (
    <div
      className={clsx(
        "flex flex-col gap-4 items-center p-4 font-semibold default-focus",
        {
          ["rounded border-2 border-black"]: border,
        },
        className
      )}
      {...props}
    >
      <time className="flex flex-col font-semibold text-center">
        <div className="text-4xl">
          <Trans id="user.finder.appointment.card.time">
            {i18n.date(actualAppointment.startAt.local().toDate(), {
              hour: "2-digit",
              minute: "2-digit",
            })}{" "}
            Uhr
          </Trans>
        </div>

        <div className="text-xl">
          <Trans id="user.finder.appointment.card.date">
            am{" "}
            {i18n.date(actualAppointment.startAt.local().toDate(), {
              day: "2-digit",
              month: "2-digit",
              year: "2-digit",
            })}
          </Trans>
        </div>
      </time>

      <p className="text-center">
        {
          vaccines[i18n.locale || "de"][actualAppointment.vaccine as Vaccine]
            .name
        }
      </p>

      <div className="text-center">
        Slots: {actualAppointment.bookings.length}/
        {actualAppointment.slotData.length} -{actualAppointment.status}
        <br />
        {actualAppointment.status !== AppointmentStatus.CANCELED && (
          <Button size="sm" onClick={handleCancelAppointment}>
            Cancel
          </Button>
        )}
      </div>
    </div>
  );
};

// apps/provider/src/lib/components/schedule/AppointmentCard.svelte
<script lang="ts">
  import { cancelAppointment } from "$lib/api";
  import { vaccines, type Vaccine } from "@impfen/common";
  import { date, locale, t, time } from "svelte-intl-precompile";
  import type { Appointment } from "vanellus";
  import { AppointmentStatus } from "vanellus";

  export let appointment: Appointment<Vaccine>;
  export let border: true | undefined = undefined;

  const handleCancelAppointment = async () => {
    await cancelAppointment(appointment);
  };

  const vaccine = vaccines[$locale][appointment.vaccine];
</script>

<div
  class="flex flex-col gap-4 items-center p-4 font-semibold default-focus"
  class:border
>
  <!-- svelte-ignore component-name-lowercase -->
  <time class="flex flex-col font-semibold text-center">
    <div class="text-4xl">
      {$t("user.finder.appointment.card.time", {
        values: {
          time: $time(appointment.startAt.local().toDate(), {
            format: "short",
          }),
        },
      })}
    </div>

    <div class="text-xl">
      {$t("user.finder.appointment.card.date", {
        values: {
          date: $date(appointment.startAt.local().toDate(), {
            format: "short",
          }),
        },
      })}
    </div>
  </time>

  <p class="text-center">
    {vaccine.name}
  </p>

  <div class="text-center">
    Slots: {appointment.bookings.length}/
    {appointment.slotData.length} -{appointment.status}
    <br />
    {#if appointment.status !== AppointmentStatus.CANCELED}
      <button class="button primary s" on:click={handleCancelAppointment}
        >Cancel</button
      >
    {/if}
  </div>
</div>
