// apps/user/src/lib/components/faq/FaqSection.svelte
<script lang="ts">
  export let title: string;
</script>

<section class="faq-section flex flex-col mb-16" {...$$restProps}>
  <h2 class="h3 section mb-5 text-lg font-semibold tracking-wider uppercase">
    {title}
  </h2>

  <div class="faq-questions flex flex-col px-8 md:gap-10 md:px-0 md:ml-6">
    <slot />
  </div>
</section>

// apps/user/src/components/faq/FaqSection.tsx
import { Title } from "@impfen/common";

export interface FaqSectionProps {
  title: string;
}

export const FaqSection: React.FC<FaqSectionProps> = ({
  children,
  title,
  ...props
}) => {
  return (
    <section className="flex flex-col mb-16" {...props}>
      <Title
        as="h3"
        variant="section"
        className="mb-5 text-lg font-semibold tracking-wider uppercase"
      >
        {title}
      </Title>

      <div className="flex flex-col px-8 md:gap-10 md:px-0 md:ml-6">
        {children}
      </div>
    </section>
  );
};
