// apps/user/src/components/finder/AppointmentCard.tsx
import { Title, Vaccine, vaccines } from "@impfen/common";
import { Trans } from "@lingui/macro";
import { useLingui } from "@lingui/react";
import clsx from "clsx";
import type { AggregatedPublicAppointment, PublicAppointment } from "vanellus";

export interface AppointmentCardProps {
  appointment: AggregatedPublicAppointment | PublicAppointment;
  className?: string;
  border?: true | undefined;
}

export const AppointmentCard: React.FC<AppointmentCardProps> = ({
  children,
  appointment,
  className,
  border = false,
  ...props
}) => {
  const { i18n } = useLingui();

  return (
    <article
      className={clsx(
        "flex flex-col gap-4 items-center p-4 font-semibold default-focus",
        {
          ["rounded border-2 border-black"]: border,
        },
        className
      )}
      {...props}
    >
      <address className="flex flex-col items-center min-w-[15rem] font-medium text-center">
        <Title variant="h3" as="h3" className="pb-4">
          {appointment.provider.name}
        </Title>
        {appointment.provider.street},
        <br />
        {appointment.provider.zipCode} {appointment.provider.city}
      </address>

      <time className="flex flex-col font-semibold text-center">
        <div className="text-4xl">
          <Trans id="user.finder.appointment.card.time">
            {i18n.date(appointment.startDate.toDate(), { timeStyle: "short" })}{" "}
            Uhr
          </Trans>
        </div>

        <div className="text-xl">
          <Trans id="user.finder.appointment.card.date">
            am{" "}
            {i18n.date(appointment.startDate.toDate(), {
              day: "2-digit",
              month: "2-digit",
              year: "2-digit",
            })}
          </Trans>
        </div>
      </time>

      <p className="text-center">
        {vaccines[i18n.locale || "de"][appointment.vaccine as Vaccine].name}
      </p>

      {/* button */}
      {children}
    </article>
  );
};

// apps/user/src/lib/components/AppointmentCard.svelte
<script lang="ts">
  import type { Vaccine } from "@impfen/common";
  import { vaccines } from "@impfen/common";
  import dayjs from "dayjs";
  import { date, locale, time } from "svelte-intl-precompile";
  import type { AggregatedPublicAppointment } from "vanellus";

  export let appointment: AggregatedPublicAppointment;
  export let border = false;

  const vaccine = vaccines[$locale][appointment.vaccine as Vaccine];
</script>

<article
  class="appointment-card"
  class:border
  on:click
  tabIndex={-1}
  {...$$restProps}
>
  <address>
    <h3>
      {appointment.provider.name}
    </h3>

    {appointment.provider.street},
    <br />
    {appointment.provider.zipCode}
    {appointment.provider.city}
  </address>

  <!-- svelte-ignore component-name-lowercase -->
  <time>
    <div>
      {$date(dayjs(appointment.startAt).toDate(), {
        weekday: "short",
        day: "2-digit",
        month: "short",
      })}
    </div>

    <div>
      um
      {$time(dayjs(appointment.startAt).toDate(), {
        hour: "2-digit",
        minute: "2-digit",
      })}
      Uhr
    </div>
  </time>

  <p>
    {vaccine.name}
  </p>

  <slot />
</article>
