// apps/user/src/lib/components/ProviderCard.svelte
<script lang="ts">
  import { t } from "svelte-intl-precompile";
  import type { PublicProvider } from "vanellus";
  import IconAccessibility from "~icons/carbon/accessibility";

  export let provider: PublicProvider;
</script>

<article class="provider-card">
  <div>
    <h2 class="h4">{provider.name}</h2>

    <address>
      {provider.street}, {provider.zipCode}
      {provider.city}
    </address>
  </div>

  {#if provider.accessible}
    <IconAccessibility aria-label={$t("user.provider-card.accessibility")} />
  {/if}
</article>

// apps/user/src/components/finder/ProviderCard.tsx
import { Accessibility24 } from "@carbon/icons-react";
import { Title } from "@impfen/common";
import clsx from "clsx";
import type { PublicProvider } from "vanellus";

export interface ProviderCardProps {
  provider: PublicProvider;
  className?: string;
}

export const ProviderCard: React.FC<ProviderCardProps> = ({
  provider,
  className,
}) => {
  return (
    <article className={clsx("provider-card", className)} key={provider.id}>
      <div>
        <Title variant="h3">{provider.name}</Title>

        <address>
          {provider.street}, {provider.zipCode} {provider.city}
        </address>
      </div>

      {provider.accessible && <Accessibility24 />}
    </article>
  );
};
