// apps/provider/src/lib/components/calendar/AppointmentCell.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { AppointmentStatus } from "vanellus";
  import type { CalendarItem } from "./CalendarItem";

  export let item: CalendarItem;

  const height = Math.floor((item.duration / 60) * 100);
  const width = Math.floor(100 / (1 + item.maxOverlap));
  const top = Math.floor((item.startAt.get("minutes") / 60) * 100);

  const i = item.overlapsWith.filter(
    (overlappingItem) => overlappingItem.overlapIndex < item.overlapIndex
  ).length;

  const left = Math.floor(i * width);
  // const tiny = height < 33 || width < 50;

  // if (tiny) {
  //   return null;
  // }

  const percentUsed = item.bookedSlots * (item.slots / 100);

  const dispatcher = createEventDispatcher<{
    open: CalendarItem;
  }>();

  const handleClick: svelte.JSX.EventHandler<
    MouseEvent,
    HTMLButtonElement
  > = () => {
    dispatcher("open", item);
  };

  const canceled = item.item.status === AppointmentStatus.CANCELED;
</script>

<button on:click={handleClick}>
  <div
    style:height={`${height}px`}
    style:min-height={`${height}px`}
    style:width={`${width}%`}
    style:top={`${top}%`}
    style:left={`${left}%`}
    style:opacity={canceled ? 0.25 : 1}
    style:background-color={canceled
      ? "lightgray"
      : `hsl(${((100 - percentUsed) / 100) * 120}, 75%, 90%)`}
  >
    <h4>
      {item.startAt.format("HH:mm")} - {item.endAt.format("HH:mm")}
    </h4>

    <div>
      {#if item.isSeries}
        SERIE -
      {/if}
      {item.bookedSlots}/{item.slots}
      {#if item.isSeries}
        <br />
        {item.items.length} x {item.items[0].duration} Min auf
        {item.items[0].slotData.length} Lanes mit {item.vaccine}
      {:else}
        " " + item.vaccine
      {/if}
    </div>

    {item.vaccine}
  </div>
</button>

<style lang="postcss">
  div {
    overflow: hidden;
    position: absolute;
    z-index: 10;
    padding: 8px;
    cursor: pointer;
  }
</style>

// apps/provider/src/components/WeekCalendar/AppointmentCell.tsx
import type { CalendarItem } from "./CalendarItem";

interface AppointmentCellProps {
  item: CalendarItem;
}

export const AppointmentCell: React.FC<AppointmentCellProps> = ({ item }) => {
  const height = Math.floor((item.duration / 60) * 100);
  const width = Math.floor(100 / (1 + item.maxOverlap));
  const top = Math.floor((item.startAt.get("minutes") / 60) * 100);

  const i = item.overlapsWith.filter(
    (overlappingItem) => overlappingItem.overlapIndex < item.overlapIndex
  ).length;

  const left = Math.floor(i * width);
  // const tiny = height < 33 || width < 50;

  // if (tiny) {
  //   return null;
  // }

  const percentUsed = item.bookedSlots * (item.slots / 100);

  return (
    <div
      style={{
        height: `${height}px`,
        minHeight: `${height}px`,
        width: `${width}%`,
        top: `${top}%`,
        left: `${left}%`,
        backgroundColor: `hsl(${((100 - percentUsed) / 100) * 120}, 88%, 43%)`,
      }}
      className="overflow-hidden hover:overflow-visible absolute z-10 hover:z-20 flex-col p-2 hover:!w-full hover:!h-auto text-xs hover:text-base hover:shadow-box opacity-80 hover:opacity-100 transition-all cursor-pointer"
    >
      <h4>
        {item.startAt.format("HH:mm")} - {item.endAt.format("HH:mm")}
      </h4>

      <div>
        {item.isSeries ? <>SERIE - </> : null}
        {item.bookedSlots}/{item.slots}
        {item.isSeries ? (
          <>
            <br />
            {item.items.length} x {item.items[0].duration} Min auf{" "}
            {item.items[0].slotData.length} Lanes mit {item.vaccine}
          </>
        ) : (
          " " + item.vaccine
        )}
      </div>

      {/* {item.vaccine} */}
    </div>
  );
};
