// apps/user/src/lib/components/ProviderCard.svelte
<script lang="ts">
  import { t } from "svelte-intl-precompile";
  import type { PublicProvider } from "vanellus";
  import IconAccessibility from "~icons/carbon/accessibility";

  export let provider: PublicProvider;
</script>

<article>
  <div>
    <h2 class="h4">{provider.name}</h2>

    <address>
      {provider.street}, {provider.zipCode}
      {provider.city}
    </address>
  </div>

  {#if provider.accessible}
    <IconAccessibility aria-label={$t("user.provider-card.accessibility")} />
  {/if}
</article>

<style lang="postcss">
  article {
    border: 2px solid var(--color-black);
    border-radius: var(--radius-l);
    padding: 1rem;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;

    &:hover {
      box-shadow: var(--shadow-highlight);
      border: 2px solid var(--color-highlight);
    }
  }
</style>

// src/components/common/ProviderCard.tsx
import { Accessibility24 } from "@carbon/icons-react";
import clsx from "clsx";
import React from "react";
import type { PublicProvider } from "types";
import { Title } from "ui";

export interface ProviderCardProps {
  provider: PublicProvider;
  className?: string;
}

export const ProviderCard: React.FC<ProviderCardProps> = ({
  provider,
  className,
}) => {
  return (
    <div
      className={clsx(
        "flex justify-between p-4 rounded-2xl border-2 border-black",
        "hover:border-highlight hover:shadow-provider",
        className
      )}
      key={provider.id}
    >
      <div>
        <Title variant="h3">{provider.name}</Title>

        <address>
          {provider.street}, {provider.zipCode} {provider.city}
        </address>
      </div>

      {provider.accessible && <Accessibility24 />}
    </div>
  );
};
