// src/ui/Field.tsx
import clsx from 'clsx';
import React from 'react';
import { useFormContext } from 'react-hook-form';
import { Error } from './Error';
import { Label } from './Label';

export interface FieldProps {
    name: string;
    className?: string;
    id?: string;
    label?: string;
    description?: string;
    inline?: boolean;
    required?: boolean;
    as?: 'div' | 'label' | 'span' | 'p';
}

export const Field: React.FC<FieldProps> = ({
    children,
    name,
    className,
    label,
    description,
    id,
    inline,
    required,
    as,
    ...props
}) => {
    const Element = as || 'div';
    const formContext = useFormContext();
    const error = formContext
        ? formContext.formState?.errors?.[name]?.message
        : false;

    return (
        <Element
            className={clsx('field', { ['field-inline']: inline }, className)}
            {...props}
        >
            {label && (
                <Label id={id} required={required}>
                    {label}
                </Label>
            )}
            {children}
            {error && <Error>{error}</Error>}
            {!error && description && <div className="hint">{description}</div>}
        </Element>
    );
};

// packages/common/src/components/Field.svelte
<script lang="ts">
  export let name: string;
  export let label: string;
  export let description = "";
  export let required = false;
  export let inline = false;
</script>

<div class:field={true} class:inline class:required>
  <slot name="label"><label class="label" for={name}>{label}</label></slot>
  <slot id={name} class="input" {required} />
  <slot name="description"><small>{description}</small></slot>
</div>
